analyzer:
  errors:
    use_build_context_synchronously: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_use_package_imports: false
    avoid_print: true
    prefer_const_constructors: true
    prefer_single_quotes: true
    curly_braces_in_flow_control_structures: true
    unnecessary_this: true
