include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    use_build_context_synchronously: ignore

linter:
  rules:
    # Common industry standard Dart/Flutter rules
    always_use_package_imports: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_single_quotes: true
    curly_braces_in_flow_control_structures: true
    unnecessary_this: true
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true
    sort_constructors_first: true
    type_annotate_public_apis: true
    avoid_unnecessary_containers: true
    avoid_returning_null_for_future: true
    prefer_final_locals: true
    prefer_final_fields: true
    avoid_redundant_argument_values: true
    avoid_return_types_on_setters: true
    avoid_types_on_closure_parameters: false
    prefer_const_literals_to_create_immutables: true
    prefer_spread_collections: true
    prefer_collection_literals: true
    avoid_empty_else: true
    avoid_init_to_null: true
    avoid_function_literals_in_foreach_calls: true
    unnecessary_new: true
    unnecessary_const: true
    unnecessary_lambdas: true
    unnecessary_overrides: true
    prefer_typing_uninitialized_variables: true
    use_rethrow_when_possible: true
    use_is_even_rather_than_modulo: true
    use_decorated_box: true
    use_colored_box: true
