name: freedom_driver
description: Driver app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  country_code_picker: ^3.1.0
  dotted_border: ^2.1.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.10.0
  gradient_borders: ^1.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  http: ^1.3.0
  intl: ^0.19.0
  lottie: ^3.2.0
  pin_code_fields: ^8.0.1
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/app_icons/
    - assets/app_images/
    - assets/nav/active_icon/
    - assets/nav/inactive_icon/
    - assets/lottie/
