name: freedomdriver
description: "Rider app for freedom"
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.7.2
dependencies:
  awesome_dialog: ^3.2.1
  awesome_snackbar_content: ^0.1.5
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  cloudinary_flutter: ^1.3.0
  country_code_picker: ^3.1.0
  country_state_city_picker: ^1.2.8
  dio: ^5.8.0+1
  dotted_border: ^3.0.1
  equatable: ^2.0.7
  file_picker: ^10.1.2
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_local_notifications: ^19.1.0
  flutter_localizations:
    sdk: flutter
  flutter_polyline_points: ^2.1.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  geocoding: ^3.0.0
  geolocator: ^14.0.0
  get: ^4.7.2
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.12.1
  gradient_borders: ^1.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  http: ^1.3.0
  http_parser: ^4.1.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  loader_overlay: ^5.0.0
  lottie: ^3.3.1
  mime: ^2.0.0
  path: ^1.9.1
  permission_handler: ^12.0.0+1
  pin_code_fields: ^8.0.1
  smooth_page_indicator: ^1.2.0+3
  socket_io_client: ^3.1.2
  timezone: ^0.10.1

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0
  change_app_package_name: ^1.5.0

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/app_icons/
    - assets/app_images/
    - assets/nav/active_icon/
    - assets/nav/inactive_icon/
    - assets/lottie/


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  min_sdk_android: 21
  image_path: "assets/app_images/bold_bcg.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#de4a0a"